main: me.redslime.Mace
version: 1.0
name: Mace
author: TheMrRedSlime
api-version: 1.13

commands:
  givemace:
    description: "Gives Mace"
    permission: mace.give
  reloadmace:
    description: "Reload Mace Plugin"
    permission: mace.reload

permissions:
  mace.give:
    description: "Mace give command"
    default: op
  mace.reload:
    description: "Mace reload command"
    default: op